### PR TITLE
Modified jsonapter.js, added params support.

### PR DESCRIPTION
**Pull request by fastcodejava**

### CODE REVIEW

**Comment by SameerSiddiqui** [comment]
Fix the test Cases!

**Comment by fastcodejava** [comment]
The Travis CI build passed!

**Comment by au2** [comment]
1) There appears to be no tests when "params[paramKey] === 'function'" (paramKeyToInput) or when "Array.isArray(contextKey)" (evaluateParamKey).   Either add tests or remove these code branches.  I think paramKeyToInput 'function' branch is not really needed since you can do similar with dataKey function branch.
2) As a follow up to 1, evaluateParamKey  "Array.isArray(contextKey)" branch calls to this.dataKeyArrayToInput without "context" and that calls to dataKeyInput instead of paramKeyInput.  That appears to be a bug.
3) Minor but please make evaluateParamKey and paramKeyInput arguments consistent (contextKey, context) -> (paramKey, params)

**Comment by fastcodejava** [comment]
Addressed the issues from @au2.
Also refactored dataKeyArrayToInput and paramKeyArrayToInput to use a common genericKeyArrayToInput.
Modified package.json to add contributors.

**Comment by fastcodejava** [comment]
Hi @au2,

Hope you had a good Labor Day weekend.
Could you please merge this whenever you have some free time?

Thanks,
--Gautam

**Pull request merged**
