### PR TITLE
Modified jsonapter.js  introduced template tag as described in the issue

### PR DESCRIPTION
**Pull request by fastcodejava**
https://github.com/amida-tech/jsonapter/issues/23.

Modified the tests and README.md.

### CODE REVIEW

**Comment by SameerSiddiqui** [comment]
Cool! Now it makes it simple.

**Comment by fastcodejava** [comment]
@au2 can you merge the pull request at your earliest convenience?

**Comment by au2** [comment]
will do tonight or over the weekend

**Comment by fastcodejava** [comment]
​Thanks @au2 , ​but it is still not done. If you're too busy could you give me the commit access to the project?

--Gautam

**Pull request merged**
