### PR TITLE
Prune implementation

### PR DESCRIPTION
**Pull request by SameerSiddiqui**
Please review!

if you like the idea- we can update documentation and release.

Thanks,
Sameer

### CODE REVIEW

**Comment by jsachs** [comment]
@austundag, I can't assign your main account, but do you want to review when you have time?

**Comment by au2** [comment]
au2 is good.  yes i will review before monday.

**Comment by au2** [comment]
1. The condition (content[key]["default"] !== null && content[key]["default"] !== undefined) is not being tested; I removed that condition from code and prune test still passes.  I think you wanted 'a' instead of 'a.d' in one of the test cases. That also means you do not have any tests for "" and []; do we need?
2. Please run full grunt before PR.
3. Otherwise I am good with the changes.  If you want to update readme please go ahead.  I think I will do a release after your changes gets in.

**Comment by SameerSiddiqui** [comment]
Ok, i am closing this one and creating a new one!

**Pull request closed without merging**
