### PR TITLE
Modified jsonapter.js to handle Existswhen with string and object.

### PR DESCRIPTION
**Pull request by fastcodejava**
Fixed the issue : https://github.com/amida-tech/jsonapter/issues/28.
Modified some tests and the README.

### CODE REVIEW

**Comment by SameerSiddiqui** [comment]
This seems to be a niceFeature!

**Comment by fastcodejava** [comment]
@au2 can you please merge the pull request at your earliest convenience?

**Comment by fastcodejava** [comment]
Thanks, if you publish it now we can start using it!

**Comment by au2** [comment]
done.

**Pull request merged**
